/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as SessionTasksChooseOrganizationRouteImport } from './routes/session-tasks/choose-organization'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SessionTasksChooseOrganizationRoute =
  SessionTasksChooseOrganizationRouteImport.update({
    id: '/session-tasks/choose-organization',
    path: '/session-tasks/choose-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/_auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/_auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/test': typeof TestRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/': typeof DashboardIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/test': typeof TestRoute
  '/session-tasks/choose-organization': typeof SessionTasksChooseOrganizationRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/session-tasks/choose-organization'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/session-tasks/choose-organization'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/_dashboard'
    | '/test'
    | '/session-tasks/choose-organization'
    | '/_dashboard/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  TestRoute: typeof TestRoute
  SessionTasksChooseOrganizationRoute: typeof SessionTasksChooseOrganizationRoute
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/session-tasks/choose-organization': {
      id: '/session-tasks/choose-organization'
      path: '/session-tasks/choose-organization'
      fullPath: '/session-tasks/choose-organization'
      preLoaderRoute: typeof SessionTasksChooseOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  TestRoute: TestRoute,
  SessionTasksChooseOrganizationRoute: SessionTasksChooseOrganizationRoute,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
